<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Mollie\Payment\Block\Loading $block */
/** @var \Magento\Framework\Escaper $escaper */

$redirectUrl = $block->getRedirectUrl();

// Magento 2.3 compatibility
isset($escaper) || $escaper = $block; // @phpstan-ignore-line
?>
<div class="mollie-loading" id="mollie-loading">
    <div class="redirect-block">
        <h1><?= $escaper->escapeHtml(__('Redirecting to Mollie')); ?></h1>
        <div class="loader"></div>
    </div>
</div>
<div class="mollie-buttons" id="mollie-buttons" style="display:none">
    <div class="redirect-block">
        <a class="button" href="<?= $escaper->escapeHtmlAttr($block->getBackUrl()); ?>">
            <?= $escaper->escapeHtml(__('Back to Checkout')); ?>
        </a>
        <a class="button" href="<?= $escaper->escapeHtmlAttr($redirectUrl); ?>">
            <?= $escaper->escapeHtml(__('Proceed Payment')); ?>
        </a>
    </div>
</div>
<script>
    window.setTimeout(function() {
        document.getElementById("mollie-loading").style.display = "none";
        document.getElementById("mollie-buttons").style.display = "block";
        window.location.href = '<?= $escaper->escapeHtml($redirectUrl); ?>';
    }, 1000);
</script>
