<?php
/**
 * Copyright © 2018 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $redirectUrl = $this->getRedirectUrl(); ?>
<div class="mollie-loading" id="mollie-loading">
    <div class="redirect-block">
        <h1><?= __('Redirecting to Mollie'); ?></h1>
        <div class="loader"></div>
    </div>
</div>
<div class="mollie-buttons" id="mollie-buttons" style="display:none">
    <div class="redirect-block">
        <a class="button" href="<?= $this->getBackUrl(); ?>">
            <?= __('Back to Checkout'); ?>
        </a>
        <a class="button" href="<?= $redirectUrl; ?>">
            <?= __('Proceed Payment'); ?>
        </a>
    </div>
</div>
<script>
    window.setTimeout(function() {
        document.getElementById("mollie-loading").style.display = "none";
        document.getElementById("mollie-buttons").style.display = "block";
        window.location.href = '<?= $redirectUrl; ?>';
    }, 1000);
</script>