<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

// Magento 2.3 compatibility
isset($escaper) || $escaper = $block; // @phpstan-ignore-line
?>
<p><?= $escaper->escapeHtml(__('The following method(s) are disabled in the Mollie Dashboard. They won\'t be available in the checkout.')); ?></p>
<ul>
    <?php foreach($block->getData('methods') as $method): ?>
        <li><?= $escaper->escapeHtml($method); ?></li>
    <?php endforeach; ?>
</ul>
