<?php

/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Mollie\Payment\Service\Config\Debug;

use Magento\Framework\App\Filesystem\DirectoryList;
use Magento\Framework\Archive\Gz;
use Magento\Framework\Archive\Tar;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\Filesystem;
use Mollie\Payment\Config;

class DebugBundleGenerator
{
    public function __construct(
        private readonly Filesystem $filesystem,
        private readonly Tar $tar,
        private readonly Gz $gz,
        private readonly Config $mollieConfig,
        /**
         * @var CollectorInterface[]
         */
        private readonly array $collectors = [],
    ) {
    }

    /**
     * Generates a debug bundle .tgz file in var/tmp/ and returns the path relative to var/.
     *
     * @throws LocalizedException
     */
    public function generate(): string
    {
        $varDirectory = $this->filesystem->getDirectoryWrite(DirectoryList::VAR_DIR);
        $token = bin2hex(random_bytes(8));
        $relativeStageDir = 'tmp/mollie-debug-' . $token;
        $relativeTar = 'tmp/mollie-debug-' . $token . '.tar';
        $relativeTgz = 'tmp/mollie-debug-' . $token . '.tgz';

        $varDirectory->create($relativeStageDir);

        try {
            $files = [];
            foreach ($this->collectors as $collector) {
                $files = array_merge($files, $collector->collect());
            }

            $varDirectory->writeFile($relativeStageDir . '/manifest.txt', $this->buildManifest($files));
            $varDirectory->writeFile($relativeStageDir . '/README.txt', $this->buildReadme());

            foreach ($files as $path => $content) {
                $dir = dirname($path);
                if ($dir !== '.') {
                    $varDirectory->create($relativeStageDir . '/' . $dir);
                }
                $varDirectory->writeFile($relativeStageDir . '/' . $path, $content);
            }

            $absoluteStageDir = $varDirectory->getAbsolutePath($relativeStageDir);
            $absoluteTar = $varDirectory->getAbsolutePath($relativeTar);
            $absoluteTgz = $varDirectory->getAbsolutePath($relativeTgz);

            $this->tar->pack($absoluteStageDir, $absoluteTar, true);
            $this->gz->pack($absoluteTar, $absoluteTgz);
        } finally {
            if ($varDirectory->isExist($relativeStageDir)) {
                $varDirectory->delete($relativeStageDir);
            }
            if ($varDirectory->isExist($relativeTar)) {
                $varDirectory->delete($relativeTar);
            }
        }

        return $relativeTgz;
    }

    public function buildFilename(): string
    {
        return 'mollie-debug-' . date('Ymd-His') . '.tgz';
    }

    private function buildManifest(array $files): string
    {
        $mollieVersion = $this->mollieConfig->getVersion();
        $lines = [
            'Mollie debug bundle',
            'Generated at: ' . date('c'),
            'Mollie extension version: ' . ($mollieVersion !== null && $mollieVersion !== ''
                ? (string)$mollieVersion
                : 'unknown'),
            '',
            'Contents:',
            '- manifest.txt: this file',
            '- README.txt: descriptions of each file in this bundle',
        ];

        $paths = array_keys($files);
        sort($paths, SORT_STRING);
        foreach ($paths as $path) {
            $lines[] = '- ' . $path;
        }

        return implode("\n", $lines) . "\n";
    }

    private function buildReadme(): string
    {
        $lines = [
            'Mollie debug bundle - README',
            '',
            'This archive is generated by the Mollie Magento 2 extension to help Mollie support',
            'diagnose issues with your store. Below is a plain-language description of each',
            'file it contains so you can review what you are sharing before sending it.',
            '',
            'Sensitive values (encryption key, database password, cache/queue/session',
            'passwords, API keys, and similar secrets) are redacted before the bundle is',
            'written. Mollie API keys are included only in their encrypted form as stored in',
            'the database; the plaintext key is never written to the bundle.',
            '',
            'Files in this bundle:',
            '',
            '- manifest.txt',
            '  A machine-friendly index listing every file in this archive.',
            '',
            '- README.txt',
            '  This file.',
            '',
        ];

        foreach ($this->collectors as $collector) {
            $lines[] = $collector->getReadmeDescription();
            $lines[] = '';
        }

        $lines[] = 'If you would prefer not to share any of the files above, you can extract the';
        $lines[] = 'archive and remove them before sending the bundle to Mollie support.';

        return implode("\n", $lines) . "\n";
    }
}
