<?php

declare(strict_types=1);

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div id="loading-mask" data-mage-init='{"loader": { "icon": "<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')); ?>"}}'></div>

<div id="mollie-order-status"><?= __('Current Status: Loading...'); ?></div>
<div id="mollie-order-error"></div>

<script>
require([
    'jquery',
    'mage/storage',
    'mage/translate',
    'loader',
], function ($, storage, __, loader) {
    var serviceUrl = '/rest/<?= $block->getData('storeCode'); ?>/V1/mollie/get-order/<?= $escaper->escapeJs($block->getData('token')); ?>';
    var statusElement = document.getElementById('mollie-order-status');
    var errorElement = document.getElementById('mollie-order-error');
    var waitTime = 100;

    $('#loading-mask').loader({
        'icon': '<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')); ?>'
    }).loader('show');

    function checkOrderStatus() {
        storage.post(serviceUrl).done(function (response) {
            statusElement.style.display = 'block';
            errorElement.style.display = 'none';

            var status = response[0].status;
            if (status === 'processing') {
                window.location.href = '/checkout/onepage/success/';
                return;
            }

            if (status === 'canceled') {
                window.location.href = '/checkout/cart';
                return;
            }

            statusElement.innerHTML = __('Current Status: %1').replace('%1', status);

            waitTime += 100;
            setTimeout(checkOrderStatus, waitTime);
        }).fail(function (error) {
            console.error('Received error: ', error);

            statusElement.style.display = 'none';
            errorElement.style.display = 'block';
            errorElement.innerHTML = __('Something went wrong while fetching order. Retrying...');
        })
    }

    checkOrderStatus();
})
</script>
