<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Mollie\Payment\Block\Product\View\ApplePay $block */

// Magento 2.3 compatibility
isset($escaper) || $escaper = $block; // @phpstan-ignore-line

if (!$block->isEnabled()) {
    return;
}
?>

<div id="product-page-mollie-apple-pay-button" data-bind="scope:'mollie-apple-pay-button'">
    <!-- ko if: canUseApplePay() -->
    <div class="<?= $escaper->escapeHtmlAttr($block->getButtonClasses()); ?>" data-bind="click: payWithApplePay">
        <span>Apple Pay</span>
    </div>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "mollie-apple-pay-button": {
                    "component": "Mollie_Payment/js/view/product/apple-pay-button",
                    "config": {
                        "formSelector": "#product_addtocart_form",
                        "currencyCode": "<?= $escaper->escapeJs($block->getCurrencyCode()); ?>",
                        "countryCode": "<?= $escaper->escapeJs($block->getCountryCode()); ?>",
                        "productName": "<?= $escaper->escapeJs($block->getProductName()); ?>",
                        "storeName": "<?= $escaper->escapeJs($block->getStoreName()); ?>",
                        "supportedNetworks": <?= /* @noEscape */ json_encode($block->getSupportedNetworks()); ?>
                    }
                }
            }
        }
    }
}
</script>
