<?php
/**
 * Copyright © 2018 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Mollie\Payment\Block\Form\Paymentlink $block
 */
$code = $block->escapeHtml($block->getMethodCode());
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= /* @noEscape */
$code; ?>" style="display:none">
    <div class="mollie-admin-method">
        <?= $block->escapeHtml(__('Create a Mollie Payment link and add this to the order email.')); ?>
        <div class="field admin__field">
            <label for="<?= $code ?>_methods" class="label admin__field-label"><span><?= $block->escapeHtml(__('Limit to the following method(s)')) ?></span></label>
            <div class="control admin__field-control">
                <select multiple="multiple" size="16" id="<?= $code ?>_methods" name="payment[limited_methods][]" class="admin__control-multiselect">
                    <option value="bancontact">Bancontact</option>
                    <option value="banktransfer">Banktransfer</option>
                    <option value="belfius">Belfius</option>
                    <option value="creditcard">Creditcard</option>
                    <option value="directdebit">SEPA Direct Debit</option>
                    <option value="eps">EPS</option>
                    <option value="giftcard">Giftcard</option>
                    <option value="giropay">Giropay</option>
                    <option value="ideal">iDEAL</option>
                    <option value="inghomepay">ING Homepay</option>
                    <option value="kbc">KBC/CBC</option>
                    <option value="klarnapaylater">Klarna Pay Later</option>
                    <option value="klarnasliceit">Klarna Slice It</option>
                    <option value="mealvoucher">Mealvoucher</option>
                    <option value="paypal">Paypal</option>
                    <option value="paysafecard">Paysafecard</option>
                    <option value="sofort">Sofort</option>
                </select>
            </div>
        </div>
        <p><?= $block->escapeHtml(__('If one method is chosen, it will skip the selection screen and the customer is sent directly to the payment method.')); ?></p>

        <div class="field admin__field">
            <label for="<?= $code ?>_days_before_expire" class="label admin__field-label"><span><?= $block->escapeHtml(__('This order expires at:')) ?></span></label>
            <div class="control admin__field-control">
                <input
                    id="<?= $code ?>_days_before_expire"
                    name="payment[days_before_expire]"
                    class="admin__control-multiselect mollie_methods_paymentlink_days_before_expire"
                    value="<?php echo $block->getExpiresAt(); ?>"
                    data-x-magent
                >

                <a href="#" class="mollie-tooltip">(i)
                    <span>
                        <?php echo __('It is not posible to use Klarna Slice it or Klarna Pay later as method when your expiry date is more than 28 days in the future, unless another maximum is agreed between the merchant and Klarna.'); ?>
                    </span>
                </a>
            </div>
        </div>
    </div>
</fieldset>

<script>
    require([
        'jquery',
        'mage/calendar'
    ], function ($) {
        $('#<?php echo $code; ?>_days_before_expire').calendar({
            dateFormat: 'yy-mm-dd',
            maxDate: 100
        });
    });
</script>
