<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Mollie\Payment\Block\Form\Pointofsale $block
 * @var \Magento\Framework\Escaper $escaper
 */
$code = $escaper->escapeHtml($block->getMethodCode());
$first = true;
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= /* @noEscape */$code; ?>" style="display:none">
    <div class="mollie-admin-method">
        <div class="field admin__field">
            <label for="<?= $code ?>_methods" class="label admin__field-label"><span><?= $escaper->escapeHtml(__('Select Terminal')) ?></span></label>
            <div class="control admin__field-control pointofsale-terminal-list">
                <?php foreach ($block->getTerminals() as $terminal): ?>
                    <label>
                        <input type="radio" name="payment[selected_terminal]" value="<?= $terminal['id']; ?>"<?= $first ? ' checked="checked"' : ''; ?>>
                        <?= $terminal['brand']; ?> <?= $terminal['model']; ?> <?= $terminal['serialNumber']; ?> <?= $terminal['description']; ?>
                    </label>
                <?php $first = false; endforeach; ?>
            </div>
        </div>
    </div>
</fieldset>
