<?php

/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Mollie\Payment\Test\Fakes\Service\Mollie;

use Mollie\Payment\Service\Mollie\ValidateProcessRequest;

class FakeValidateProcessRequest extends ValidateProcessRequest
{
    private ?array $response = null;

    public function setResponse(array $response): void
    {
        $this->response = $response;
    }

    public function execute(): array
    {
        if ($this->response !== null) {
            return $this->response;
        }

        return parent::execute(); // TODO: Change the autogenerated stub
    }
}
