<?php
/**
 * Copyright © 2018 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @see \Mollie\Payment\Block\Adminhtml\System\Config\Form\Compatibility\Checker
 * @var \Mollie\Payment\Block\Adminhtml\System\Config\Form\Compatibility\Checker $block
 */
?>
<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {
        var resultSpan = jQuery('#result_compatibility');
        jQuery('#compatibility_button').click(function () {
            var params = {};
            new Ajax.Request('<?= $block->getAjaxUrl() ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    resultSpan.find('.connecting').show();
                    resultSpan.find('.result').hide();
                },
                onSuccess: function (response) {
                    console.log(response);
                    resultSpan.find('.connecting').hide();
                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        var json = response.responseJSON;
                        if (typeof json.msg != 'undefined') {
                            resultText = json.msg;
                        }
                    }
                    resultSpan.find('.result').show();
                    resultSpan.find('.result').html(resultText);
                }
            });
        });

    });
</script>
<?= $block->getButtonHtml() ?>