<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Mollie\Payment\Block\Adminhtml\System\Config\Form\Compatibility\Checker;

/**
 * @see Checker
 * @var Checker $block
 * @var SecureHtmlRenderer $secureRenderer
 */

$scriptString = '
    require([
        \'jquery\',
        \'mage/translate\',
        \'prototype\',
    ], function (jQuery, \$t) {
        var resultSpan = jQuery(\'#result_compatibility\');
        jQuery(\'#compatibility_button\').click(function () {
            var params = {};
            new Ajax.Request(\'' . $block->getAjaxUrl() . '\', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    resultSpan.find(\'.connecting\').show();
                    resultSpan.find(\'.result\').hide();
                },
                onSuccess: function (response) {
                    resultSpan.find(\'.connecting\').hide();
                    var resultText = \'\';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        var json = response.responseJSON;
                        if (typeof json.msg != \'undefined\') {
                            resultText = json.msg;
                        } else {
                            resultText = \$t(\'Invalid response received. This indicates an unknown problem.\');
                        }
                    }
                    resultSpan.find(\'.result\').show();
                    resultSpan.find(\'.result\').html(resultText);
                }
            });
        });

    });
';

// @phpstan-ignore-next-line
if (isset($secureRenderer)) {
    echo $secureRenderer->renderTag('script', [], $scriptString, false);
}

// @phpstan-ignore-next-line
if (!isset($secureRenderer)) {
    echo '<script>' . $scriptString . '</script>';
}

echo $block->getButtonHtml();
