<?php
/**
 * Copyright © 2018 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block Mollie\Payment\Block\Adminhtml\Render\Header
 */
?>
<div class="mm-block-mollie">
    <button id="mm-mollie-button_test" title="<?= $block->escapeUrl(__('Run Self-test')); ?>"
            type="button" class="action-default scalable"
            data-mage-init='{"Mollie_Payment/js/button-functions": {}}'
    >
        <i class="mm-mollie-icon__list-unordered-four"></i>
        <span><?= $block->escapeUrl(__('Run Self-test')); ?></span>
    </button>

    <a class="helpbutton" href="https://www.mollie.com/dashboard/settings/profiles" target="_blank"></a>

    <p>
        <strong>Developed by Magmodules.</strong>
        A Magento only eCommerce Agency located in the Netherlands.
    </p>

    <table>
        <tbody>
        <tr>
            <td>
                <div class="icon1"></div>
                <a href="https://www.magmodules.eu/" target="_blank">Visit Magmodules.eu</a>
            </td>
            <td>
                <div class="icon2"></div>
                <a href="https://www.magmodules.eu/contact-us.html" target="_blank">Extension Support</a>
            </td>
			<td>
                <div class="icon3"></div>
                <a href="https://www.mollie.nl/bedrijf/contact" target="_blank">Contact Mollie B.V.</a>
            </td>
        </tr>
        </tbody>
    </table>
</div>