<?php
/**
 * Copyright © 2017 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block Mollie\Payment\Block\Adminhtml\Render\Header
 */
?>
<div class="mm-block-mollie">
    <a class="helpbutton" href="https://www.mollie.com/dashboard/settings/profiles" target="_blank"></a>
    <p>
        <strong>Developed by Magmodules.</strong>
        A Magento only eCommerce Agency located in the Netherlands.
    </p>
    <table>
        <tbody>
        <tr>
            <td>
                <div class="icon1"></div>
                <a href="https://www.magmodules.eu/" target="_blank">Visit Magmodules.eu</a>
            </td>
            <td>
                <div class="icon2"></div>
                <a href="https://www.magmodules.eu/contact-us.html" target="_blank">Extension Support</a>
            </td>
			<td>
                <div class="icon3"></div>
                <a href="https://www.mollie.nl/bedrijf/contact" target="_blank">Contact Mollie B.V.</a>
            </td>
        </tr>
        </tbody>
    </table>
</div>