<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="mm-block-mollie">
    <a class="helpbutton" href="https://www.mollie.com/dashboard/settings/profiles" target="_blank"></a>

    <p>
        <strong>Mollie has it's own configuration tab.</strong><br>
        Click here to <a href="<?php echo $this->getUrl('adminhtml/system_config/edit/section/mollie_general'); ?>">go to the Mollie configuration</a>.
    </p>
</div>