<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var PaymentMethodsHeader $block */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Mollie\Payment\Block\Adminhtml\Render\PaymentMethodsHeader;

?>
<div class="mm-block-mollie">
    <a class="helpbutton" href="https://www.mollie.com/dashboard/settings/profiles" target="_blank"></a>

    <p>
        <strong>Mollie has it's own configuration tab.</strong><br>
        Click here to <a href="<?= $escaper->escapeHtmlAttr($block->getUrl('adminhtml/system_config/edit/section/mollie_general')); ?>">go to the Mollie configuration</a>.
    </p>
</div>
