<?php
/**
 * Copyright © 2018 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var \Mollie\Payment\Block\Info\Base $block
 * @see \Mollie\Payment\Block\Info\Base
 */
use Mollie\Payment\Model\Methods\Voucher;

$specificInfo = $block->getSpecificInformation();
$status = $block->getPaymentStatus();
?>
<div class="mollie-method">
    <img src="<?= $block->escapeUrl($block->getViewFileUrl('Mollie_Payment::images/' . $block->getPaymentImage())) ?>"/>
    <?= $block->escapeHtml($block->getMethod()->getTitle()); ?>
    <?php if ($block->getMethod() instanceof Voucher): ?>
    |
    <?php
    echo __(
        '%1 using Voucher, %2 direct.',
        $block->formatPrice($block->getAmountPaidByVoucher()),
        $block->formatPrice($block->getRemainderAmount())
    );
    ?>
    <?php $block->getMethod(); ?>
    <?php endif; ?>
    <table class="data-table admin__table-secondary">
        <tbody>
            <?php if ($block->getCheckoutType()): ?>
                <tr>
                    <th><?= __('Checkout Type'); ?></th>
                    <td class="mollie-checkout-type"><?= ucfirst($block->getCheckoutType()); ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($block->getCheckoutUrl() && $status == 'created'): ?>
                <tr>
                    <th><?= __('Checkout Url'); ?></th>
                    <td>
                        <?= $block->getCheckoutUrl(); ?>
                        <span class="mollie-copy-url" data-url="<?= $block->getCheckoutUrl(); ?>" title="<?php echo __('Copy'); ?>">
                            &#x2398;
                        </span>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if ($block->getExpiresAt() && $status == 'created'): ?>
                <tr>
                    <th><?= __('Valid Until'); ?></th>
                    <td><?= $block->getExpiresAt(); ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($block->getPaymentStatus()): ?>
                <tr>
                    <th><?= __('Payment Status'); ?></th>
                    <td>
                        <span class="mollie-payment-status"><?= ucfirst($status); ?></span>
                        <?php if ($block->isKlarnaMethod() && $status == 'authorized'): ?>
                            <a href="#" class="mollie-tooltip">(i)
                                <span><?= __('Please ship order to capture Klarna payment'); ?></span>
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if ($dashboardUrl = $block->getDashboardUrl()): ?>
                <tr>
                    <th><?= __('Mollie ID'); ?></th>
                    <td>
                        <a href="<?php echo $dashboardUrl; ?>" target="_blank" class="mollie-order-id">
                            <?php echo $block->getMollieId() ?: __('View in Mollie dashboard'); ?>
                        </a>
                        <span class="mollie-copy-url" data-url="<?php echo $dashboardUrl; ?>" title="<?php echo __('Copy'); ?>">
                            &#x2398;
                        </span>
                    </td>
                </tr>
            <?php endif; ?>
            <tr>
                <th><?= __('Update Payment Status'); ?></th>
                <td>
                    <button type="button" class="fetch-mollie-payment-status"><?= __('Fetch Status'); ?></button>
                    <a href="#" class="mollie-tooltip">(i)
                        <span>
                            <?= __('The payment-status will updated automatically by default, but in case of any interruption you can use this function to fetch the payment status manually.'); ?>
                        </span>
                    </a>
                </td>
            </tr>
            <tr class="mollie-order-status-result" style="display: none;"></tr>
        </tbody>
    </table>
</div>
<?= $block->getChildHtml() ?>

<script type="text/x-magento-init">
    {
        ".mollie-method": {
            "Mollie_Payment/js/order/fetch-order-status": {
                "endpoint": "<?php echo $block->getUrl('mollie/action/fetchOrderStatus'); ?>",
                "order_id": "<?php echo $block->getOrderId(); ?>"
            }
        },
        ".mollie-copy-url": {
            "Mollie_Payment/js/copy-url": {}
        }
    }
</script>
