<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var Base $block
 * @see Base
 */

use Mollie\Payment\Block\Info\Base;

?>
<?= $block->escapeHtml($block->getMethod()->getTitle()); ?>{{pdf_row_separator}}

<?php if ($specificInfo = $block->getSpecificInformation()):?>
    <?php foreach ($specificInfo as $label => $value):?>
        <?= $block->escapeHtml($label) ?>:
        <?= $block->escapeHtml(implode(' ', $block->getValueAsArray($value)));?>
        {{pdf_row_separator}}
    <?php endforeach; ?>
<?php endif;?>

<?= $block->escapeHtml(implode('{{pdf_row_separator}}', $block->getChildPdfAsArray())); ?>
